"""empty message

Revision ID: 102462bd2a5f
Revises: 147d474b8f32
Create Date: 2024-01-27 17:24:15.099851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102462bd2a5f'
down_revision = '147d474b8f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('friendId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friendId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('emojiId', sa.Integer(), nullable=False),
    sa.Column('messageId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emojiId'], ['emojis.id'], ),
    sa.ForeignKeyConstraint(['messageId'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'server', ['server_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('server_id')

    op.drop_table('reactions')
    op.drop_table('friends')
    # ### end Alembic commands ###